_wandb:
    value:
        cli_version: 0.22.3
        e:
            i7v66o2bsd7cg0lxzf78wy3mesgjzwbt:
                args:
                    - run
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1999496015872"
                        used: "1810584006656"
                email: s27669@pjwstk.edu.pl
                executable: C:\Users\adaml\miniconda3\envs\asi-ml\python.exe
                git:
                    commit: 4cda708a7ce37cf25ef7936544984f2690ca354a
                    remote: https://github.com/PJ-s28184/asi-project.git
                gpu: NVIDIA GeForce RTX 4070 SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 7168
                      memoryTotal: "12878610432"
                      name: NVIDIA GeForce RTX 4070 SUPER
                      uuid: GPU-b51a9bd0-266e-d10f-1e4e-2b2ae8e9dfb1
                host: bestia
                memory:
                    total: "33411727360"
                os: Windows-10-10.0.26100-SP0
                program: -m __main__
                python: CPython 3.11.14
                root: C:\Users\adaml\Pictures\asi-project
                startedAt: "2025-10-30T19:57:31.828689Z"
                writerId: i7v66o2bsd7cg0lxzf78wy3mesgjzwbt
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
            "4": 3.11.14
            "5": 0.22.3
            "8":
                - 2
                - 3
            "10":
                - 20
            "12": 0.22.3
            "13": windows-amd64
