_wandb:
    value:
        cli_version: 0.22.3
        e:
            n9uzu5yxep28081dsejdiy1nubrioxhw:
                args:
                    - run
                email: kacper.ziebacz01@gmail.com
                executable: /opt/homebrew/Caskroom/miniconda/base/envs/asi-ml/bin/python
                git:
                    commit: ae4597d0dafcea7db38e93cb317781dc7023c4e8
                    remote: https://github.com/PJ-s28184/asi-project.git
                host: 172.23.72.107.wi-fi.pjwstk.edu.pl
                os: macOS-15.6-arm64-arm-64bit
                program: /opt/homebrew/Caskroom/miniconda/base/envs/asi-ml/bin/kedro
                python: CPython 3.11.14
                root: /Users/kacperziebacz/Desktop/asi-project
                startedAt: "2025-10-31T08:15:26.789328Z"
                writerId: n9uzu5yxep28081dsejdiy1nubrioxhw
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
            "4": 3.11.14
            "5": 0.22.3
            "10":
                - 20
            "12": 0.22.3
            "13": darwin-arm64
